Всё перезалил
seregako/java-filmorate pull request #3
Opened 2023-03-04 12:57 UTC by seregako

2023-03-05 07:40 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-05 07:40 UTC, FanaticFiz commented on pom.xml
> +	<properties>
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Объявление переменных тоже требует внимания!
Статики описываются первыми, хотя логеру и не обязательно быть таковым!

У остальных не хватает модификаторов доступа!

А инжект зависимости и вовсе лучше делать через конструктор!

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> list = store.getAllFilms().entrySet()
List<Film> list - плохое название переменной!

Название должно сказать мне что в этом списке лежит, а то что это список я и сам вижу!

Но это на будущее, поскольку тут вообще можно было бы обойтись без выделения переменной - сразу написав `return`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@PathVariable("id") int getId) {
Название переменной! `getId` ???

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("storage now " + store.getAllFilms());
В логере принято передавать значение по шаблону `{}`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else throw new IllegalArgumentException("There is no film with id " + film.getId());
В Java не экономят на `{}`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (store.getAllFilms().containsKey(film.getId())) {
`store.getAllFilms().containsKey(film.getId())` 
Всё вот это должно быть в твоём store, как отдельный метод который отвечает на вопрос есть ли... 

Понимаешь?
Не берем из хранилища все фильмы и тут проверяем, а в хранилище создаём метод!

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else throw new IllegalArgumentException("There is no film with id " + film.getId());
Исключение лучше завести своё, назвать его, в данном случае, нужно: `NotFoundException`
И использовать его нужно будет для всех сущностей в проекте.

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Validated
Ну к этому сервису, к его коду те же вопросы что и к предыдущему.
Повторятся не буду...

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank()
Делай отступы между полями, когда много аннотаций накидано, всё сливается...

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/store/FilmStore.java
> +    public void putFilm(Film film) {
Не называй методы в хранилище как HTTP глаголы...

Там `PUT`или `PATCH` а тут это `update`

`POST -> create/add`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/store/FilmStore.java
> +    public Map<Integer, Film> getAllFilms() {
Храни фильмы как тебе удобно... но отдавай их как список `List`

2023-03-05 07:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/store/UserStore.java
> +        if(user.getName()==null||user.getName().isEmpty()){
Этот же код я видел в контроллере! ))
Зачем оно в двух местах...

2023-03-06 07:40 UTC, seregako commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Каюсь, вопрос был не как код написать, а как его сюда залить)

2023-03-06 18:42 UTC, FanaticFiz approved these changes

2023-03-06 18:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("storage now: {} " + store.giveAllFilms());
Вот так

`log.info("storage now: {}", store.giveAllFilms());`

2023-03-06 18:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int id = 0;
Если у тебя уже на этом этапе есть хранилище то и id должен был бы быть там.
Но с этим можно в следующий раз разобраться.

2023-03-06 18:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/store/FilmStore.java
> +    public Film giveFilm(int filmId) {
`giveFilm` -> `get()` or `getById()`

2023-03-09 11:01 UTC, merged