Первая попытка
seregako/java-filmorate pull request #4
Opened 2023-03-12 18:23 UTC by seregako

2023-03-13 19:33 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final int FILMSLIST_DEFAULT_SIZE = 10;
static переменные описываются первыми, поэтому должно начинаться с логера.
Хотя ему и не обязательно быть static!

Что касается самой константы: FILMSLIST_DEFAULT_SIZE -> POPULAR_FILMS_DEFAULT_SIZE
Ну т.е. вот прям вот так вот в лоб и назови ))

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStore;
Теперь в контроллере не должно быть хранилищ, только сервисы.

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //private int id = 0;
Удаляй старый код...

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStore.giveAllFilms();
filmStore.giveAllFilms(); -> `filmStore.finsAll()`

Не нужно добавлять films поскольку это понятно из самого названия сервиса.

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!filmStore.getFilms().containsKey(filmId)) {
В хранилище должен быть метод с кодом 
`filmStore.getFilms().containsKey(filmId)`
с названием, например: `exist(filmId)`.

Вызывать мы его будем из сервиса! И бросать исключение если фильма нет будем из сервиса. 
А в контроллере будет дергать метод сервиса: `filmService.getById(filmId)`
А в контроллере

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("storage now: {} " + filmStore.giveAllFilms() + "\n List of popularity" + filmStore.getPopularFilms());
Обрати внимание на логгер. В нём удобно сделана подстановка значений, нет необходимости собирать строку из частей:
`log.info("Storage now: {} List of popularity {}", filmStore.giveAllFilms(), filmStore.getPopularFilms());`

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public InMemoryFilmStorage getStore() {
?

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +import org.springframework.http.HttpStatus;
К этому контроллеру применимы те же замечания. Поработай над ним.

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage storage;
Почему не использован интерфейс FilmStorage ?
Он же не для красоты был создан!

С таким подходом, буквально в следующей работе, реализация будет заменена, а код в сервисе по-идее не придется менять!

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/strorage/FilmStorage.java
> +  void updateFilm(Film film);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `filmStorage.updateFilm()`

Получается масло-масляное! 

Лучше: `filmStorage.update()` `userService.update()`

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/strorage/FilmStorage.java
> +    void clearFilmsStorage();
`clearFilmsStorage() -> clear()`

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/strorage/FilmStorage.java
> +    Film giveFilm(int filmId);
`giveFilm -> findById()` - давай в хранилищах использовать глагол `find`, а в сервисах `get`

`filmService.getById()`
`filmStorage.findById()` - и в хранилищах удобно использовать Optional - попробуй его освоить!

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/strorage/InMemoryFilmStorage.java
> +        } else throw new IllegalArgumentException("There is no film with id " + film.getId());
Не кидаем исключения из хранилища - это работа сервисов.

2023-03-13 19:33 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else throw new ResponseStatusException(
Классы исключений должны быть свои!
Называй их по тем статусам которые они порождают для клиента.
Например HttpStatus.NOT_FOUND - должно бросаться исключение: `NotFoundException`

2023-03-17 19:32 UTC, FanaticFiz approved these changes

2023-03-17 19:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("storage now: {} " + service.getAll() + "\n List of popularity" + service.getPopular(10));
Еще раз про работу со значениями в логере.
Не надо складывать строки! Параметры передаются отдельно...

`log.info("storage now: {} List of popularity: {}", service.getAll(), service.getPopular(10));`

2023-03-17 19:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/NoFilmIdException.java
> +public class NoFilmIdException extends RuntimeException{
Не нужно создавать по классу исключению на каждую сущность...
Класс один общий: `NotFoundException`, а в сообщении ты пишешь подробности что не найдено.

2023-03-17 19:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else throw new NoUserIdException("No user with id " + userId);
Не экономим на `{}` - это Java тут так не принято!

Кроме этого, надо отрефакторить.

```
    public void addLike(int filmId, int userId) {
        if (!userStorage.exist(userId)) {
            throw new NoUserIdException("No user with id " + userId);
        }
        
        Film film = filmStorage.find(filmId)
                               .orElseThrow(() -> new NoFilmIdException("Wrong film Id"));
        film.getLikes().add(userId);
        
        filmStorage.update(film);
    }
```

Первое - инвертировали условие, чтобы метод начинался с условия выхода из метода
Второе - избавились от else. Зачем нам лишние вложенности!

2023-03-17 19:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/strorage/FilmStorage.java
> +    Map<Integer, Film> getFilms();
`getFilms` - не используется, удалить!
`public` - не указываем, это же интерфейс!

2023-03-18 05:22 UTC, seregako commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("storage now: {} " + service.getAll() + "\n List of popularity" + service.getPopular(10));
Спасибо за обратную связь! Недочёты устранил

2023-04-12 16:41 UTC, merged